import React, { createContext, useContext, useState, useEffect } from 'react';

export type ThemeMode = 'system' | 'day' | 'night';
export type Language = 'en' | 'zh' | 'es' | 'fr' | 'ar' | 'ru' | 'de' | 'pt' | 'ja' | 'hi';
export type SubscriptionTier = 'basic' | 'premium' | 'maximum';

export interface TickerItem {
  id: string;
  label: string;
  price: string;
  change: string;
  isUp: boolean;
  isVisible: boolean;
}

interface ConfigContextType {
  language: Language;
  themeMode: ThemeMode;
  subscription: SubscriptionTier;
  setLanguage: (lang: Language) => void;
  setThemeMode: (mode: ThemeMode) => void;
  setSubscription: (tier: SubscriptionTier) => void;
  t: (key: string) => string;
  tickerItems: TickerItem[];
  setTickerItems: React.Dispatch<React.SetStateAction<TickerItem[]>>;
}

const defaultTickerItems: TickerItem[] = [
  { id: 'c5', label: 'C5 (W. Australia/China)', price: '$8.45', change: '+0.12', isUp: true, isVisible: true },
  { id: 'c3', label: 'C3 (Tubarao/China)', price: '$18.20', change: '-0.35', isUp: false, isVisible: true },
  { id: 'c4', label: 'C4 (RB/Rotterdam)', price: '$14.80', change: '+0.08', isUp: true, isVisible: true },
  { id: 'p1a', label: 'P1A (USG/Rotterdam)', price: '$12.10', change: '+0.22', isUp: true, isVisible: true },
  { id: 'p2a', label: 'P2A (USG/Far East)', price: '$28.50', change: '-0.15', isUp: false, isVisible: true },
  { id: 's1b', label: 'S1B (ECSA/Rotterdam)', price: '$15.30', change: '+0.05', isUp: true, isVisible: true },
  { id: 'bci', label: 'BCI', price: '2,845', change: '+45', isUp: true, isVisible: true },
  { id: 'bpi', label: 'BPI', price: '1,952', change: '-12', isUp: false, isVisible: true },
  { id: 'bsi', label: 'BSI', price: '1,240', change: '+8', isUp: true, isVisible: true },
];

const ConfigContext = createContext<ConfigContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    inbox_parser: "INBOX_PARSER",
    vessel_monitor: "VESSEL_MONITOR",
    cargo_desk: "CARGO_DESK",
    analytics: "ANALYTICS",
    fleet_map: "FLEET_MAP",
    settings: "SETTINGS",
    manage_sources: "MANAGE_SOURCES",
    notifications: "NOTIFICATIONS",
    preferences: "PREFERENCES",
    selection_desk: "SELECTION_DESK",
    contact_list: "CONTACT_LIST",
    apply_changes: "APPLY_CHANGES",
    ai_assistant: "AI_ASSISTANT",
    ai_connect: "AI_CONNECT",
    broker_id: "BROKER_ID",
    automation: "AUTOMATION",
    legal_docs: "LEGAL_DOCS",
    language: "LANGUAGE",
    theme: "THEME",
    interface_language: "INTERFACE_LANGUAGE",
    ui_theme_variant: "UI_THEME_VARIANT",
    subscription: "SUBSCRIPTION PLAN",
    pricing_title: "Select your trading edge",
    pricing_subtitle: "Unlock institutional-grade data, predictive AI, and seamless workflow integration.",
    tier_basic: "Basic",
    tier_premium: "Premium",
    tier_maximum: "Maximum",
    tier_basic_desc: "Essential tools for independent brokers.",
    tier_premium_desc: "Advanced terminal for active trading desks.",
    tier_maximum_desc: "Enterprise-grade intelligence & APIs.",
    up_to_10_emails_day: "Up to 500 emails/day parsed",
    basic_parsing: "Standard NLP extraction",
    standard_support: "Standard email support",
    single_user: "1 User license",
    unlimited_emails: "Unlimited email parsing",
    advanced_ai_parsing: "Advanced Contextual AI Models",
    priority_support: "24/7 Priority Support",
    up_to_5_users: "Up to 5 User licenses",
    vessel_tracking: "Live AIS Vessel Tracking",
    automated_drafts: "Automated Fixture Drafting",
    everything_in_premium: "Everything in Premium tier",
    unlimited_users: "Unlimited User licenses",
    dedicated_manager: "Dedicated Account Manager",
    custom_ai_models: "Custom-trained AI Models",
    api_access: "Full API Access",
    whitelabel_reports: "White-label Reporting",
    current_plan: "CURRENT PLAN",
    upgrade_now: "UPGRADE NOW",
    processing: "PROCESSING...",
    export: "EXPORT",
    new_cargo: "NEW CARGO",
    new_vessel: "NEW VESSEL",
    id_tag: "ID TAG",
    commodity: "COMMODITY",
    quantity: "QUANTITY",
    load_port: "LOAD PORT",
    discharge_port: "DISCHARGE PORT",
    actions: "ACTIONS",
    vessel_name: "VESSEL NAME",
    type: "TYPE",
    dwt: "DWT",
    built: "BUILT",
    open_port: "OPEN PORT",
    open_date: "OPEN DATE",
    status: "STATUS",
    cargo: "CARGO",
    vessel: "VESSEL",
    selection: "SELECTION",
    inbox: "INBOX",
    global_display_units: "GLOBAL DISPLAY UNITS",
    weight: "WEIGHT",
    distance: "DISTANCE",
    currency: "CURRENCY",
    live_market_ticker: "LIVE MARKET TICKER",
    localization_note: "Changing the interface language will update all system hex-identifiers, terminal labels, and AI-generated summaries to your selected regional dialect.",
    config_matrix: "CONFIGURATION MATRIX",
    system_params: "SYSTEM PARAMETERS AND AI CONTROL",
    cargo_interface: "CARGO INTERFACE",
    active_records: "ACTIVE RECORDS",
    search_cargo: "Search cargo register...",
    cargo_specs: "CARGO SPECIFICATIONS",
    total_quantity: "TOTAL QUANTITY",
    stowage_factor: "STOWAGE FACTOR",
    logistics_protocol: "LOGISTICS PROTOCOL",
    laycan: "LAYCAN",
    charterer: "CHARTERER",
    terms: "TERMS",
    ai_profiler: "AI COMMODITY PROFILER",
    owner_comments: "OWNER COMMENTS",
    private_notes: "PRIVATE NOTES",
    match_tonnage: "MATCH AVAILABLE TONNAGE",
    mark_active: "MARK ACTIVE",
    mark_completed: "MARK COMPLETED",
    vessel_interface: "VESSEL INTERFACE",
    search_vessel: "Search vessel register...",
    vessel_specs: "VESSEL SPECIFICATIONS",
    vessel_capacity: "DWT CAPACITY",
    grt_nrt: "GRT / NRT",
    holds_vol: "HOLDS / VOL",
    match_cargo: "MATCH AVAILABLE CARGOES",
    documentation: "DOCUMENTATION",
    operations: "OPERATIONS",
    search: "Search",
    trial_welcome_title: "Welcome to Cargo Desk App!",
    trial_welcome_message: "Your first 30 days are completely free! Enjoy full access to all features. After the trial period ends, you will be asked to select a subscription plan.",
    trial_welcome_button: "Start Free Trial",
    trial_expired_title: "Trial Period Ended",
    trial_expired_message: "Your 30-day free trial has expired. To continue using all features, please choose a subscription plan.",
    choose_plan: "Choose Plan"
  },
  ru: {
    inbox_parser: "ПАРСЕР ВХОДЯЩИХ",
    vessel_monitor: "МОНИТОР СУДОВ",
    cargo_desk: "ГРУЗОВОЙ СТОЛ",
    analytics: "АНАЛИТИКА",
    fleet_map: "КАРТА ФЛОТА",
    settings: "НАСТРОЙКИ",
    manage_sources: "ИСТОЧНИКИ",
    notifications: "УВЕДОМЛЕНИЯ",
    preferences: "ПРЕДПОЧТЕНИЯ",
    selection_desk: "СТОЛ ПОДБОРА",
    contact_list: "СПИСОК КОНТАКТОВ",
    apply_changes: "СОХРАНИТЬ ИЗМЕНЕНИЯ",
    ai_assistant: "ИИ ПОМОЩНИК",
    ai_connect: "ПОДКЛЮЧЕНИЕ ИИ",
    broker_id: "ПРОФИЛЬ БРОКЕРА",
    automation: "АВТОМАТИЗАЦИЯ",
    legal_docs: "ДОКУМЕНТЫ",
    language: "ЯЗЫК",
    theme: "ТЕМА",
    interface_language: "ЯЗЫК ИНТЕРФЕЙСА",
    ui_theme_variant: "ЦВЕТОВАЯ ТЕМА",
    subscription: "ПОДПИСКА",
    pricing_title: "Выберите ваш тариф",
    pricing_subtitle: "Получите доступ к данным институционального уровня, прогнозирующему ИИ и интеграции рабочих процессов.",
    tier_basic: "Базовая",
    tier_premium: "Премиум",
    tier_maximum: "Максимум",
    tier_basic_desc: "Основные инструменты для независимых брокеров.",
    tier_premium_desc: "Продвинутый терминал для активных брокеров.",
    tier_maximum_desc: "Корпоративная версия и доступ к API.",
    up_to_10_emails_day: "До 500 писем/день",
    basic_parsing: "Стандартный NLP-парсинг",
    standard_support: "Техподдержка по email",
    single_user: "Лицензия на 1 пользователя",
    unlimited_emails: "Безлимитный парсинг писем",
    advanced_ai_parsing: "Продвинутый ИИ-анализ контекста",
    priority_support: "Приоритетная поддержка 24/7",
    up_to_5_users: "До 5 пользователей",
    vessel_tracking: "Отслеживание судов (Live AIS)",
    automated_drafts: "Автоматические черновики сделок",
    everything_in_premium: "Всё, что включено в Премиум",
    unlimited_users: "Неограниченно пользователей",
    dedicated_manager: "Персональный менеджер",
    custom_ai_models: "Тренировка ИИ под вас",
    api_access: "Полный доступ к API",
    whitelabel_reports: "White-label отчеты",
    current_plan: "ТЕКУЩИЙ",
    upgrade_now: "ПЕРЕЙТИ",
    processing: "ОБРАБОТКА...",
    export: "ЭКСПОРТ",
    new_cargo: "НОВЫЙ ГРУЗ",
    new_vessel: "НОВОЕ СУДНО",
    id_tag: "ID-МЕТКА",
    commodity: "ГРУЗ",
    quantity: "КОЛИЧЕСТВО",
    load_port: "ПОРТ ПОГРУЗКИ",
    discharge_port: "ПОРТ ВЫГРУЗКИ",
    actions: "ДЕЙСТВИЯ",
    vessel_name: "НАЗВАНИЕ СУДНА",
    type: "ТИП",
    dwt: "ДЕДВЕЙТ",
    built: "ГОД ПОСТРОЙКИ",
    open_port: "ОТКРЫТЫЙ ПОРТ",
    open_date: "ДАТА",
    status: "СТАТУС",
    cargo: "ГРУЗЫ",
    vessel: "ФЛОТ",
    selection: "ПОДБОР",
    inbox: "ПОЧТА",
    global_display_units: "ГЛОБАЛЬНЫЕ ЕДИНИЦЫ ИЗМЕРЕНИЯ",
    weight: "ВЕС",
    distance: "РАССТОЯНИЕ",
    currency: "ВАЛЮТА",
    live_market_ticker: "РЫНОЧНЫЙ ТИКЕР",
    localization_note: "Изменение языка интерфейса обновит все системные метки, названия терминалов и сводки ИИ на выбранный вами язык.",
    config_matrix: "МАТРИЦА НАСТРОЕК",
    system_params: "СИСТЕМНЫЕ ПАРАМЕТРЫ И КОНТРОЛЬ ИИ",
    cargo_interface: "ГРУЗОВОЙ ИНТЕРФЕЙС",
    active_records: "АКТИВНЫЕ ЗАПИСИ",
    search_cargo: "Поиск по реестру грузов...",
    cargo_specs: "ХАРАКТЕРИСТИКИ ГРУЗА",
    total_quantity: "ОБЩЕЕ КОЛИЧЕСТВО",
    stowage_factor: "КОЭФФИЦИЕНТ УКЛАДКИ",
    logistics_protocol: "ЛОГИСТИЧЕСКИЙ ПРОТОКОЛ",
    laycan: "ЛЕЙКЭН",
    charterer: "ФРАХТОВАТЕЛЬ",
    terms: "УСЛОВИЯ",
    ai_profiler: "ИИ ПРОФИЛИРОВАНИЕ ГРУЗА",
    owner_comments: "КОММЕНТАРИИ ВЛАДЕЛЬЦА",
    private_notes: "ЛИЧНЫЕ ЗАМЕТКИ",
    match_tonnage: "ПОДОБРАТЬ ДОСТУПНЫЙ ТОННАЖ",
    mark_active: "ОТМЕТИТЬ КАК АКТИВНЫЙ",
    mark_completed: "ОТМЕТИТЬ КАК ЗАВЕРШЕННЫЙ",
    vessel_interface: "ИНТЕРФЕЙС СУДНА",
    search_vessel: "Поиск по реестру судов...",
    vessel_specs: "ХАРАКТЕРИСТИКИ СУДНА",
    vessel_capacity: "ВМЕСТИМОСТЬ (ДЕДВЕЙТ)",
    grt_nrt: "БРТ / НРТ",
    holds_vol: "ТРЮМЫ / ОБЪЕМ",
    match_cargo: "ПОДОБРАТЬ ДОСТУПНЫЕ ГРУЗЫ",
    documentation: "ДОКУМЕНТАЦИЯ",
    operations: "ОПЕРАЦИИ",
    search: "Поиск",
    trial_welcome_title: "Добро пожаловать в Cargo Desk App!",
    trial_welcome_message: "Первый месяц использования абсолютно бесплатен! Наслаждайтесь полным доступом ко всем функциям. По истечении 30 дней вам будет предложено выбрать тарифный план.",
    trial_welcome_button: "Начать бесплатный период",
    trial_expired_title: "Пробный период истек",
    trial_expired_message: "Ваш бесплатный 30-дневный период подошел к концу. Чтобы продолжить использовать все функции приложения, выберите подходящий тарифный план.",
    choose_plan: "Выбрать тариф"
  },
  zh: {
    "inbox_parser": "收件箱解析器",
    "vessel_monitor": "船舶监控",
    "cargo_desk": "货运管理",
    "analytics": "分析中心",
    "fleet_map": "舰队地图",
    "settings": "设置",
    "manage_sources": "管理来源",
    "notifications": "通知",
    "preferences": "首选项",
    "selection_desk": "选船中心",
    "contact_list": "联系人列表",
    "apply_changes": "应用更改",
    "ai_assistant": "AI助手",
    "ai_connect": "AI连接",
    "broker_id": "经纪人ID",
    "automation": "自动化",
    "legal_docs": "法律文件",
    "language": "语言",
    "theme": "主题",
    "interface_language": "界面语言",
    "ui_theme_variant": "UI主题变量",
    "subscription": "订阅计划",
    "pricing_title": "选择您的交易优势",
    "pricing_subtitle": "解锁机构级数据、预测性AI和无缝工作流集成。",
    "tier_basic": "基础版",
    "tier_premium": "高级版",
    "tier_maximum": "旗舰版",
    "tier_basic_desc": "独立经纪人的基本工具。",
    "tier_premium_desc": "面向活跃交易中心的高级终端。",
    "tier_maximum_desc": "企业级智能与API。",
    "up_to_10_emails_day": "每天最多500封邮件",
    "basic_parsing": "标准NLP提取",
    "standard_support": "标准邮件支持",
    "single_user": "1个用户许可证",
    "unlimited_emails": "无限制的邮件解析",
    "advanced_ai_parsing": "高级上下文AI模型",
    "priority_support": "优先支持",
    "up_to_5_users": "最多5个用户",
    "vessel_tracking": "实时AIS监控",
    "automated_drafts": "自动草稿",
    "everything_in_premium": "高级版所有功能",
    "unlimited_users": "无限制用户",
    "dedicated_manager": "专属客户经理",
    "custom_ai_models": "定制AI模型",
    "api_access": "完整API访问",
    "whitelabel_reports": "白底报告",
    "current_plan": "当前计划",
    "upgrade_now": "立即升级",
    "processing": "处理中...",
    "export": "导出",
    "new_cargo": "新货物",
    "new_vessel": "新船舶",
    "id_tag": "ID标签",
    "commodity": "商品",
    "quantity": "数量",
    "load_port": "装货港",
    "discharge_port": "卸货港",
    "actions": "动作",
    "vessel_name": "船名",
    "type": "类型",
    "dwt": "载重吨",
    "built": "建造年份",
    "open_port": "开港",
    "open_date": "开港日期",
    "status": "状态",
    "cargo": "货物",
    "vessel": "船舶",
    "selection": "选择",
    "inbox": "收件箱",
    "global_display_units": "全局显示单位",
    "weight": "重量",
    "distance": "距离",
    "currency": "货币",
    "live_market_ticker": "实时市场动态",
    "localization_note": "更改界面语言将更新系统内的各项标识与标签。",
    "config_matrix": "配置矩阵",
    "system_params": "系统参数和AI控制",
    "cargo_interface": "货物界面",
    "active_records": "记录",
    "search_cargo": "搜索货物...",
    "cargo_specs": "货物规格",
    "total_quantity": "总数量",
    "stowage_factor": "积载因数",
    "logistics_protocol": "物流协议",
    "laycan": "受载期",
    "charterer": "租船人",
    "terms": "条款",
    "ai_profiler": "AI商品配置",
    "owner_comments": "船东评论",
    "private_notes": "私人笔记",
    "match_tonnage": "匹配可用运力",
    "mark_active": "标记为激活",
    "mark_completed": "标记为已完成",
    "vessel_interface": "船舶界面",
    "search_vessel": "搜索船舶...",
    "vessel_specs": "船舶规格",
    "vessel_capacity": "载重吨容量",
    "grt_nrt": "总吨 / 净吨",
    "holds_vol": "货舱 / 容积",
    "match_cargo": "匹配可用货物",
    "documentation": "文档",
    "operations": "运营",
    "search": "搜索",
    "trial_welcome_title": "欢迎使用 Cargo DeskApp!",
    "trial_welcome_message": "您的前30天完全免费！试用期结束后，我们会请您选择一个订阅计划。",
    "trial_welcome_button": "开始免费试用",
    "trial_expired_title": "试用期结束",
    "trial_expired_message": "您30天的试用期已结束。要继续使用，请选择一个计划。",
    "choose_plan": "选择计划"
},
  es: {
    "inbox_parser": "ANALIZADOR DE ENTRADA",
    "vessel_monitor": "MONITOR DE BUQUES",
    "cargo_desk": "MESA DE CARGA",
    "analytics": "ANALÍTICA",
    "fleet_map": "MAPA DE FLOTA",
    "settings": "AJUSTES",
    "manage_sources": "GESTIONAR FUENTES",
    "notifications": "NOTIFICACIONES",
    "preferences": "PREFERENCIAS",
    "selection_desk": "MESA DE SELECCIÓN",
    "contact_list": "LISTA DE CONTACTOS",
    "apply_changes": "APLICAR CAMBIOS",
    "ai_assistant": "ASISTENTE IA",
    "ai_connect": "CONECTAR IA",
    "broker_id": "ID DEL CORREDOR",
    "automation": "AUTOMATIZACIÓN",
    "legal_docs": "DOCUMENTOS LEGALES",
    "language": "IDIOMA",
    "theme": "TEMA",
    "interface_language": "IDIOMA DE INTERFAZ",
    "ui_theme_variant": "VARIANTE DE TEMA UI",
    "subscription": "PLAN DE SUSCRIPCIÓN",
    "pricing_title": "Selecciona tu ventaja comercial",
    "pricing_subtitle": "Desbloquea datos institucionales, IA predictiva e integración perfecta.",
    "tier_basic": "Básico",
    "tier_premium": "Premium",
    "tier_maximum": "Máximo",
    "tier_basic_desc": "Herramientas esenciales para corredores.",
    "tier_premium_desc": "Terminal avanzada para mesas activas.",
    "tier_maximum_desc": "Inteligencia y APIs empresariales.",
    "up_to_10_emails_day": "Hasta 500 correos/día",
    "basic_parsing": "Extracción PNL estándar",
    "standard_support": "Soporte estándar",
    "single_user": "1 Usuario",
    "unlimited_emails": "Correos ilimitados",
    "advanced_ai_parsing": "Modelos IA Avanzados",
    "priority_support": "Soporte Prioritario 24/7",
    "up_to_5_users": "Hasta 5 Usuarios",
    "vessel_tracking": "Rastreo AIS en vivo",
    "automated_drafts": "Borradores automáticos",
    "everything_in_premium": "Todo en el plan Premium",
    "unlimited_users": "Usuarios ilimitados",
    "dedicated_manager": "Gerente de cuentas dedicado",
    "custom_ai_models": "Modelos IA personalizados",
    "api_access": "Acceso total a API",
    "whitelabel_reports": "Reportes marca blanca",
    "current_plan": "PLAN ACTUAL",
    "upgrade_now": "ACTUALIZAR AHORA",
    "processing": "PROCESANDO...",
    "export": "EXPORTAR",
    "new_cargo": "NUEVA CARGA",
    "new_vessel": "NUEVO BUQUE",
    "id_tag": "ETIQUETA ID",
    "commodity": "MERCANCÍA",
    "quantity": "CANTIDAD",
    "load_port": "PUERTO DE CARGA",
    "discharge_port": "PUERTO DE DESCARGA",
    "actions": "ACCIONES",
    "vessel_name": "NOMBRE DEL BUQUE",
    "type": "TIPO",
    "dwt": "DWT",
    "built": "AÑO",
    "open_port": "PUERTO ABIERTO",
    "open_date": "FECHA ABIERTA",
    "status": "ESTADO",
    "cargo": "CARGA",
    "vessel": "BUQUE",
    "selection": "SELECCIÓN",
    "inbox": "BANDEJA",
    "global_display_units": "UNIDADES GLOBALES",
    "weight": "PESO",
    "distance": "DISTANCIA",
    "currency": "MONEDA",
    "live_market_ticker": "TICKER DEL MERCADO EN VIVO",
    "localization_note": "Cambiar el idioma de interfaz actualizará las etiquetas y resúmenes de IA.",
    "config_matrix": "MATRIZ DE CONFIGURACIÓN",
    "system_params": "PARÁMETROS DEL SISTEMA Y CONTROL DE IA",
    "cargo_interface": "INTERFAZ DE CARGA",
    "active_records": "REGISTROS ACTIVOS",
    "search_cargo": "Buscar en registro de carga...",
    "cargo_specs": "ESPECIFICACIONES DE CARGA",
    "total_quantity": "CANTIDAD TOTAL",
    "stowage_factor": "FACTOR DE ESTIBA",
    "logistics_protocol": "PROTOCOLO LOGÍSTICO",
    "laycan": "LAYCAN",
    "charterer": "FLETADOR",
    "terms": "TÉRMINOS",
    "ai_profiler": "PERFILADOR DE MERCANCÍA IA",
    "owner_comments": "COMENTARIOS DEL ARMADOR",
    "private_notes": "NOTAS PRIVADAS",
    "match_tonnage": "BUSCAR TONELAJE",
    "mark_active": "MARCAR ACTIVO",
    "mark_completed": "MARCAR COMPLETADO",
    "vessel_interface": "INTERFAZ DE BUQUE",
    "search_vessel": "Buscar en registro de buques...",
    "vessel_specs": "ESPECIFICACIONES DE BUQUE",
    "vessel_capacity": "CAPACIDAD DWT",
    "grt_nrt": "GRT / NRT",
    "holds_vol": "BODEGAS / VOL",
    "match_cargo": "BUSCAR CARGAS",
    "documentation": "DOCUMENTACIÓN",
    "operations": "OPERACIONES",
    "search": "Buscar",
    "trial_welcome_title": "¡Bienvenido a Cargo Desk App!",
    "trial_welcome_message": "Tus primeros 30 días son gratuitos. ¡Disfruta acceso total!",
    "trial_welcome_button": "Comenzar Prueba",
    "trial_expired_title": "Prueba Finalizada",
    "trial_expired_message": "Tu prueba de 30 días ha expirado. Selecciona un plan para continuar.",
    "choose_plan": "Elegir Plan"
},
  fr: {
    "inbox_parser": "ANALYSEUR DE BOÎTE",
    "vessel_monitor": "MONITEUR DE NAVIRES",
    "cargo_desk": "BUREAU DES CARGAISONS",
    "analytics": "ANALYTIQUE",
    "fleet_map": "CARTE DE LA FLOTTE",
    "settings": "PARAMÈTRES",
    "manage_sources": "GÉRER LES SOURCES",
    "notifications": "NOTIFICATIONS",
    "preferences": "PRÉFÉRENCES",
    "selection_desk": "BUREAU DE SÉLECTION",
    "contact_list": "LISTE DE CONTACTS",
    "apply_changes": "APPLIQUER LES CHANGEMENTS",
    "ai_assistant": "ASSISTANT IA",
    "ai_connect": "CONNEXION IA",
    "broker_id": "ID DU COURTIER",
    "automation": "AUTOMATISATION",
    "legal_docs": "DOCUMENTS LÉGAUX",
    "language": "LANGUE",
    "theme": "THÈME",
    "interface_language": "LANGUE DE L'INTERFACE",
    "ui_theme_variant": "VARIANTE DE THÈME",
    "subscription": "PLAN D'ABONNEMENT",
    "pricing_title": "Sélectionnez votre avantage",
    "pricing_subtitle": "Débloquez les données institutionnelles et l'IA prédictive.",
    "tier_basic": "Basique",
    "tier_premium": "Premium",
    "tier_maximum": "Maximum",
    "tier_basic_desc": "Outils essentiels pour courtiers.",
    "tier_premium_desc": "Terminal avancé pour bureaux.",
    "tier_maximum_desc": "Intelligence et APIs d'entreprise.",
    "up_to_10_emails_day": "Jusqu'à 500 emails/jour",
    "basic_parsing": "Extraction PNL standard",
    "standard_support": "Support standard",
    "single_user": "1 Utilisateur",
    "unlimited_emails": "Emails illimités",
    "advanced_ai_parsing": "Modèles IA avancés",
    "priority_support": "Support Prioritaire 24/7",
    "up_to_5_users": "Jusqu'à 5 Utilisateurs",
    "vessel_tracking": "Suivi AIS en direct",
    "automated_drafts": "Brouillons automatiques",
    "everything_in_premium": "Tout du plan Premium",
    "unlimited_users": "Utilisateurs illimités",
    "dedicated_manager": "Gestionnaire de compte",
    "custom_ai_models": "Modèles IA sur mesure",
    "api_access": "Accès total API",
    "whitelabel_reports": "Rapports marque blanche",
    "current_plan": "PLAN ACTUEL",
    "upgrade_now": "METTRE À NIVEAU",
    "processing": "TRAITEMENT...",
    "export": "EXPORTER",
    "new_cargo": "NOUVELLE CARGAISON",
    "new_vessel": "NOUVEAU NAVIRE",
    "id_tag": "TAG ID",
    "commodity": "MARCHANDISE",
    "quantity": "QUANTITÉ",
    "load_port": "PORT DE CHARGEMENT",
    "discharge_port": "PORT DE DÉCHARGEMENT",
    "actions": "ACTIONS",
    "vessel_name": "NOM DU NAVIRE",
    "type": "TYPE",
    "dwt": "DWT",
    "built": "ANNÉE",
    "open_port": "PORT OUVERT",
    "open_date": "DATE D'OUVERTURE",
    "status": "STATUT",
    "cargo": "CARGAISON",
    "vessel": "NAVIRE",
    "selection": "SÉLECTION",
    "inbox": "RÉCEPTION",
    "global_display_units": "UNITÉS GLOBALES",
    "weight": "POIDS",
    "distance": "DISTANCE",
    "currency": "DEVISE",
    "live_market_ticker": "TICKER DU MARCHÉ",
    "localization_note": "Le changement de langue mettra à jour l'interface matérielle.",
    "config_matrix": "MATRICE DE CONFIGURATION",
    "system_params": "PARAMÈTRES SYSTÈME ET IA",
    "cargo_interface": "INTERFACE CARGAISON",
    "active_records": "ENREGISTREMENTS ACTIFS",
    "search_cargo": "Chercher cargaison...",
    "cargo_specs": "SPÉCIFICATIONS CARGAISON",
    "total_quantity": "QUANTITÉS TOTALES",
    "stowage_factor": "FACTEUR D'ARRIMAGE",
    "logistics_protocol": "PROTOCOLE LOGISTIQUE",
    "laycan": "LAYCAN",
    "charterer": "AFFRÉTEUR",
    "terms": "CONDITIONS",
    "ai_profiler": "PROFILAGE IA MARCHANDISE",
    "owner_comments": "COMMENTAIRES PROPRIÉTAIRE",
    "private_notes": "NOTES PRIVÉES",
    "match_tonnage": "TROUVER NAVIRE",
    "mark_active": "MARQUER ACTIF",
    "mark_completed": "MARQUER TERMINÉ",
    "vessel_interface": "INTERFACE NAVIRE",
    "search_vessel": "Chercher navire...",
    "vessel_specs": "SPÉCIFICATIONS NAVIRE",
    "vessel_capacity": "CAPACITÉ DWT",
    "grt_nrt": "GRT / NRT",
    "holds_vol": "CALES / VOL",
    "match_cargo": "TROUVER CARGAISON",
    "documentation": "DOCUMENTATION",
    "operations": "OPÉRATIONS",
    "search": "Chercher",
    "trial_welcome_title": "Bienvenue dans Cargo Desk!",
    "trial_welcome_message": "Vos 30 premiers jours sont totalement gratuits.",
    "trial_welcome_button": "Démarrer l'essai",
    "trial_expired_title": "Essai terminé",
    "trial_expired_message": "Votre essai de 30 jours est expiré. Choisissez un plan.",
    "choose_plan": "Choisir le Plan"
},
  ar: { 
    inbox_parser: "محلل_الوارد", 
    settings: "الإعدادات",
    preferences: "تفضيلات",
    apply_changes: "تطبيق_التغييرات"
  },
  de: {
    "inbox_parser": "POSTEINGANG",
    "vessel_monitor": "SCHIFFSMONITOR",
    "cargo_desk": "FRACHT-DESK",
    "analytics": "ANALYTIK",
    "fleet_map": "FLOTTENKARTE",
    "settings": "EINSTELLUNGEN",
    "manage_sources": "QUELLEN VERWALTEN",
    "notifications": "BENACHRICHTIGUNGEN",
    "preferences": "PRÄFERENZEN",
    "selection_desk": "AUSWAHL-DESK",
    "contact_list": "KONTAKTLISTE",
    "apply_changes": "ÄNDERUNGEN ÜBERNEHMEN",
    "ai_assistant": "KI-ASSISTENT",
    "ai_connect": "KI-VERBINDUNG",
    "broker_id": "MAKLER-ID",
    "automation": "AUTOMATISIERUNG",
    "legal_docs": "RECHTSDOKUMENTE",
    "language": "SPRACHE",
    "theme": "DESIGN",
    "interface_language": "OBERFLÄCHENSPRACHE",
    "ui_theme_variant": "DESIGN-VARIANTE",
    "subscription": "ABONNEMENT",
    "pricing_title": "Wählen Sie Ihren Plan",
    "pricing_subtitle": "Freischaltung von institutionellen Daten und KI.",
    "tier_basic": "Basis",
    "tier_premium": "Premium",
    "tier_maximum": "Maximum",
    "tier_basic_desc": "Essentielle Tools für Makler.",
    "tier_premium_desc": "Erweitertes Terminal.",
    "tier_maximum_desc": "Enterprise Intelligenz & APIs.",
    "up_to_10_emails_day": "Bis zu 500 E-Mails/Tag",
    "basic_parsing": "Standard-NLP",
    "standard_support": "Standard-Support",
    "single_user": "1 Benutzer",
    "unlimited_emails": "Unbegrenzte E-Mails",
    "advanced_ai_parsing": "Erweiterte KI-Modelle",
    "priority_support": "24/7 Prioritäts-Support",
    "up_to_5_users": "Bis zu 5 Benutzer",
    "vessel_tracking": "Live-AIS-Tracking",
    "automated_drafts": "Automatische Entwürfe",
    "everything_in_premium": "Alles in Premium",
    "unlimited_users": "Unbegrenzte Benutzer",
    "dedicated_manager": "Dedizierter Account-Manager",
    "custom_ai_models": "Eigene KI-Modelle",
    "api_access": "Voller API-Zugriff",
    "whitelabel_reports": "White-Label-Berichte",
    "current_plan": "AKTUELLER PLAN",
    "upgrade_now": "JETZT UPGRADEN",
    "processing": "VERARBEITUNG...",
    "export": "EXPORTIEREN",
    "new_cargo": "NEUE FRACHT",
    "new_vessel": "NEUES SCHIFF",
    "id_tag": "ID-TAG",
    "commodity": "WARE",
    "quantity": "MENGE",
    "load_port": "LADEHAFEN",
    "discharge_port": "LÖSCHHAFEN",
    "actions": "AKTIONEN",
    "vessel_name": "SCHIFFSNAME",
    "type": "TYP",
    "dwt": "DWT",
    "built": "BAUJAHR",
    "open_port": "OFFENER HAFEN",
    "open_date": "OFFENES DATUM",
    "status": "STATUS",
    "cargo": "FRACHT",
    "vessel": "SCHIFF",
    "selection": "AUSWAHL",
    "inbox": "POSTEINGANG",
    "global_display_units": "GLOBALE EINHEITEN",
    "weight": "GEWICHT",
    "distance": "DISTANZ",
    "currency": "WÄHRUNG",
    "live_market_ticker": "LIVE-MARKT-TICKER",
    "localization_note": "Ändert die Sprache der gesamten Benutzeroberfläche.",
    "config_matrix": "KONFIGURATIONSMATRIX",
    "system_params": "SYSTEM & KI PARAMETER",
    "cargo_interface": "FRACHTSCHNITTSTELLE",
    "active_records": "AKTIVE DATENSÄTZE",
    "search_cargo": "Fracht suchen...",
    "cargo_specs": "FRACHTSPEZIFIKATIONEN",
    "total_quantity": "GESAMTMENGE",
    "stowage_factor": "STAUKOEFFIZIENT",
    "logistics_protocol": "LOGISTIKPROTOKOLL",
    "laycan": "LAYCAN",
    "charterer": "CHARTERER",
    "terms": "BEDINGUNGEN",
    "ai_profiler": "KI WAREN-PROFILER",
    "owner_comments": "EIGNERKOMMENTARE",
    "private_notes": "PRIVATE NOTIZEN",
    "match_tonnage": "TONNAGE SUCHEN",
    "mark_active": "ALS AKTIV MARKIEREN",
    "mark_completed": "ALS ABGESCHLOSSEN MARKIEREN",
    "vessel_interface": "SCHIFFSSCHNITTSTELLE",
    "search_vessel": "Schiff suchen...",
    "vessel_specs": "SCHIFFSSPEZIFIKATIONEN",
    "vessel_capacity": "DWT KAPAZITÄT",
    "grt_nrt": "GRT / NRT",
    "holds_vol": "RÄUME / VOL",
    "match_cargo": "FRACHT SUCHEN",
    "documentation": "DOKUMENTATION",
    "operations": "OPERATIONEN",
    "search": "Suchen",
    "trial_welcome_title": "Willkommen bei Cargo Desk!",
    "trial_welcome_message": "Ihre ersten 30 Tage sind absolut kostenlos.",
    "trial_welcome_button": "Testversion Starten",
    "trial_expired_title": "Testzeitraum Abgelaufen",
    "trial_expired_message": "Ihre 30-tägige Testversion ist abgelaufen. Wählen Sie einen Plan.",
    "choose_plan": "Plan Wählen"
},
  pt: {
    "inbox_parser": "ANÁLISE DE ENTRADA",
    "vessel_monitor": "MONITOR DE NAVIOS",
    "cargo_desk": "MESA DE CARGAS",
    "analytics": "ANALÍTICA",
    "fleet_map": "MAPA DA FROTA",
    "settings": "CONFIGURAÇÕES",
    "manage_sources": "GERENCIAR FONTES",
    "notifications": "NOTIFICAÇÕES",
    "preferences": "PREFERÊNCIAS",
    "selection_desk": "MESA DE SELEÇÃO",
    "contact_list": "LISTA DE CONTATOS",
    "apply_changes": "APLICAR MUDANÇAS",
    "ai_assistant": "ASSISTENTE IA",
    "ai_connect": "CONECTAR IA",
    "broker_id": "ID DO CORRETOR",
    "automation": "AUTOMAÇÃO",
    "legal_docs": "DOCUMENTOS LEGAIS",
    "language": "IDIOMA",
    "theme": "TEMA",
    "interface_language": "IDIOMA DA INTERFACE",
    "ui_theme_variant": "VARIANTE DO TEMA UI",
    "subscription": "PLANO DE ASSINATURA",
    "pricing_title": "Selecione seu plano",
    "pricing_subtitle": "Desbloqueie inteligência e integração profissional.",
    "tier_basic": "Básico",
    "tier_premium": "Premium",
    "tier_maximum": "Máximo",
    "tier_basic_desc": "Ferramentas essenciais.",
    "tier_premium_desc": "Terminal avançado.",
    "tier_maximum_desc": "Inteligência corporativa e APIs.",
    "up_to_10_emails_day": "Até 500 emails/dia",
    "basic_parsing": "Extração PNL padrão",
    "standard_support": "Suporte padrão",
    "single_user": "1 Usuário",
    "unlimited_emails": "Emails ilimitados",
    "advanced_ai_parsing": "Modelos IA Avançados",
    "priority_support": "Suporte 24/7 Prioritário",
    "up_to_5_users": "Até 5 Usuários",
    "vessel_tracking": "Rastreamento AIS ao vivo",
    "automated_drafts": "Rascunhos automatizados",
    "everything_in_premium": "Tudo no plano Premium",
    "unlimited_users": "Usuários ilimitados",
    "dedicated_manager": "Gerente de conta",
    "custom_ai_models": "Modelos IA personalizados",
    "api_access": "Acesso total à API",
    "whitelabel_reports": "Relatórios White-label",
    "current_plan": "PLANO ATUAL",
    "upgrade_now": "ATUALIZAR",
    "processing": "PROCESSANDO...",
    "export": "EXPORTAR",
    "new_cargo": "NOVA CARGA",
    "new_vessel": "NOVO NAVIO",
    "id_tag": "TAG DE ID",
    "commodity": "MERCADORIA",
    "quantity": "QUANTIDADE",
    "load_port": "PORTO DE CARGA",
    "discharge_port": "PORTO DE DESCARGA",
    "actions": "AÇÕES",
    "vessel_name": "NOME DO NAVIO",
    "type": "TIPO",
    "dwt": "DWT",
    "built": "ANO",
    "open_port": "PORTO ABERTO",
    "open_date": "DATA ABERTA",
    "status": "STATUS",
    "cargo": "CARGA",
    "vessel": "NAVIO",
    "selection": "SELEÇÃO",
    "inbox": "ENTRADA",
    "global_display_units": "UNIDADES GLOBAIS",
    "weight": "PESO",
    "distance": "DISTÂNCIA",
    "currency": "MOEDA",
    "live_market_ticker": "TICKER DE MERCADO AO VIVO",
    "localization_note": "Mudar o idioma altera toda a interface.",
    "config_matrix": "MATRIZ DE CONFIGURAÇÃO",
    "system_params": "PARÂMETROS & IA",
    "cargo_interface": "INTERFACE DE CARGA",
    "active_records": "REGISTROS ATIVOS",
    "search_cargo": "Buscar cargas...",
    "cargo_specs": "ESPECIFICAÇÕES DA CARGA",
    "total_quantity": "QUANTIDADE TOTAL",
    "stowage_factor": "FATOR DE ESTIVA",
    "logistics_protocol": "PROTOCOLO LOGÍSTICO",
    "laycan": "LAYCAN",
    "charterer": "FRETADOR",
    "terms": "TERMOS",
    "ai_profiler": "PERFILADOR IA",
    "owner_comments": "COMENTÁRIOS DO ARMADOR",
    "private_notes": "NOTAS PRIVADAS",
    "match_tonnage": "BUSCAR TONELAGEM",
    "mark_active": "MARCAR ATIVO",
    "mark_completed": "MARCAR CONCLUÍDO",
    "vessel_interface": "INTERFACE DO NAVIO",
    "search_vessel": "Buscar navios...",
    "vessel_specs": "ESPECIFICAÇÕES DO NAVIO",
    "vessel_capacity": "CAPACIDADE DWT",
    "grt_nrt": "GRT / NRT",
    "holds_vol": "PORÕES / VOL",
    "match_cargo": "BUSCAR CARGAS",
    "documentation": "DOCUMENTAÇÃO",
    "operations": "OPERAÇÕES",
    "search": "Buscar",
    "trial_welcome_title": "Bem-vindo ao Cargo Desk!",
    "trial_welcome_message": "Seus primeiros 30 dias são totalmente grátis.",
    "trial_welcome_button": "Começar Teste",
    "trial_expired_title": "Teste Expirado",
    "trial_expired_message": "Seus 30 dias expiraram. Escolha um plano.",
    "choose_plan": "Escolher Plano"
},
  ja: { 
    inbox_parser: "インボックスパーサー", 
    settings: "設定",
    preferences: "設定環境",
    apply_changes: "変更を適用"
  },
  hi: { 
    inbox_parser: "इनबॉक्स पार्सर", 
    settings: "सेटिंग्स",
    preferences: "वरीयताएँ",
    apply_changes: "परिवर्तन लागू करें"
  }
};

export const ConfigProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLang = localStorage.getItem('app_language');
    if (savedLang && (['en', 'ru', 'zh', 'es', 'fr', 'ar', 'de', 'pt', 'ja', 'hi'] as string[]).includes(savedLang)) {
      return savedLang as Language;
    }
    const browserLang = navigator.language.split('-')[0].toLowerCase();
    const supportedLangs: Language[] = ['en', 'ru', 'zh', 'es', 'fr', 'ar', 'de', 'pt', 'ja', 'hi'];
    return supportedLangs.includes(browserLang as Language) ? (browserLang as Language) : 'en';
  });
  const [themeMode, setThemeMode] = useState<ThemeMode>(() => (localStorage.getItem('app_theme_mode') as ThemeMode) || 'system');
  const [subscription, setSubscription] = useState<SubscriptionTier>('basic');
  const [tickerItems, setTickerItems] = useState<TickerItem[]>(defaultTickerItems);

  useEffect(() => {
    localStorage.setItem('app_theme_mode', themeMode);

    const applyTheme = () => {
      const isSystemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      if (themeMode === 'night' || (themeMode === 'system' && isSystemDark)) {
        document.documentElement.classList.add('dark');
        document.documentElement.style.colorScheme = 'dark';
      } else {
        document.documentElement.classList.remove('dark');
        document.documentElement.style.colorScheme = 'light';
      }
    };

    applyTheme();

    if (themeMode === 'system') {
      const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
      const listener = () => applyTheme();
      mediaQuery.addEventListener('change', listener);
      return () => mediaQuery.removeEventListener('change', listener);
    }
  }, [themeMode]);

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <ConfigContext.Provider value={{ language, themeMode, subscription, setLanguage, setThemeMode, setSubscription, t, tickerItems, setTickerItems }}>
      {children}
    </ConfigContext.Provider>
  );
};

export const useConfig = () => {
  const context = useContext(ConfigContext);
  if (!context) throw new Error('useConfig must be used within ConfigProvider');
  return context;
};
